name: Update Financial Data

on:
  schedule:
    # Chạy vào 9:00 AM UTC hàng ngày (4:00 PM Vietnam time)
    - cron: '0 9 * * *'
    # Chạy vào 1:00 PM UTC hàng ngày (8:00 PM Vietnam time)
    - cron: '0 13 * * *'
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
          - name: Fetch financial data
      run: |
        python scripts/fetch_data_github.py
    
    - name: Generate HTML report
      run: |
        python scripts/generate_html_report.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "Update financial data - $(date)"
        git push
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages
